development:
  adapter: postgresql
  encoding: unicode
  database: notifyme_development
  pool: 5
  username: dev
  password: testtest
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: notifyme_test
  pool: 5
  username: dev
  password: testtest
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: notifyme_production
  pool: 5
  username: dev
  password: testtest
  host: localhost
  port: 5432
